### ISSUE TITLE
1차 동영상 어디서 볼 수 있을까요~?

### ISSUE THREAD

**Issue by pluto1019** [yamoo9/JJ_CAMP#1]
안녕하세요^^
강의 듣고있는 조창훈입니다.

1차 강의만 올려주신다고 하셨는데 혹시 올려주셨는지해서요??

**Comment by yamoo9** [comment]
### JJ 정복 CAMP 2016년 6월 18일자 영상 자료

아래 링크를 클릭하여 Youtube 영상 강의를 시청하시면 됩니다.
(2016년 9월 27일 현재. 동영상은 비공개 상태입니다)
- ~~[JJ_CAMP__2016.06.18___01](https://youtu.be/PvcLR4c9KRo)~~
- ~~[JJ_CAMP__2016.06.18___02](https://youtu.be/K3yNSQRRhJU)~~
- ~~[JJ_CAMP__2016.06.18___03](https://youtu.be/cg-ok2NwvhM)~~
