### ISSUE TITLE
자꾸 수업 외적인 질문 드려서 죄송합니다^^;;

### ISSUE THREAD

**Issue by pluto1019** [yamoo9/JJ_CAMP#10]
안녕하세요.

지난시간에 레이어팝업관련 웹접근성 한 번 보여주셨는데
그부분 관련 참고 사이트좀 알수있을까요?

더 나아가 웹접근성 관련 참고 사이트나 서적 추천부탁드립니다.

자꾸 수업외 질문 드려서 죄송합니다~~

**Comment by yamoo9** [comment]
레이어팝업(모달 윈도우) 관련 접근성 레퍼런스는 아래 글을 참고하시면 좋습니다.
W3C에서 공식으로 제작자에게 구현 방법을 사례 별로 제공하고 있습니다.

[wai-aria-practices](https://www.w3.org/TR/wai-aria-practices/#dialog_modal)

## 

접근성 서적은 국내에 다음과 같이 출간되었습니다. [[#참고](http://book.naver.com/search/search.nhn?sm=sta_hty.book&sug=&where=nexearch&query=%EC%A0%91%EA%B7%BC%EC%84%B1)]
- 웹 접근성 웹 표준 완벽 가이드
- 웹 접근성 프로젝트 시작하기
- 웹 접근성과 품질인증
