### ISSUE TITLE
비동기 통신을 위한 이벤트 구문

### ISSUE THREAD

**Issue by sussjini** [yamoo9/JJ_CAMP#13]
지난 강의 시간 잘 들었습니다. 
- 비동기 통신을 위한 이벤트 구문에 대해 매우 재밌게 들었는데요 한가지 궁금한것이 
  html을 요청할경우 각각의 html 파일을 다 따로 만들어야 하는건가요?
- json에 대해 잘 설명된 책이 있을까요? 웹에서도 많은 정보가 있지만 정리된것을 보고싶어서 ㅎㅎ 
- 수업시간에 보여주신 비동기통신 관련 pdf를 못받은거 같아서요~ 받을수 있을까요?

**Comment by yamoo9** [comment]
HTML 파일을 비동기 통신으로 로드하고자 할 경우, HTML 페이지 전부가 아닌 콘텐츠 부분만 각 HTML 파일에 추가하여 로드하면 됩니다. 예를 들어 아래처럼 페이지에서 변경될 콘텐츠 부분만 마크업 된 코드를 포함한 문서를 만들어 주면 됩니다.

``` html
<h3>Ajax를 사용한 비동기 통신</h3>
<p>비동기 통신을 사용하기 위해서는 먼저...</p>
```

## 

JSON 참고 자료 링크 드려요 ^^
- [json.org, JSON 개요](http://www.json.org/json-ko.html)
- [MDN, JSON(JavaScript 객체 표기법)](https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Global_Objects/JSON)
- [생활코딩, JSON](https://opentutorials.org/course/1375/6844)

## 

[Ajax 수업 자료 PDF](https://github.com/yamoo9/JJ_CAMP/blob/master/PDF/16%20Javascript%20%EC%BD%94%EC%96%B4-%20AJAX.pdf) 올려져 있습니다. ^^
