### ISSUE TITLE
js 코드 내에 변수 할당 관련 문의 드립니다.

### ISSUE THREAD

**Issue by nicekkong** [yamoo9/JJ_CAMP#15]
토요일에 진행된 JS 1주차 첫번째 수업 내용중 질문이 있습니다.
BOM 객체 관련 두번째 예제 중에서 변수 처리중 다음과 같은 부분이 있었습니다.

`assignClassDetection.old_class = init_class;
`

위와 같이 변수를 할당 하는 것이, 전역 변수로 `var old_class;`를 선언하여 사용하는 것 대비 어떤 장점이 있을까요?
위와 같이 메서드의 변수를 사용하는 것이 어떤 상황에서 유용하게 사용되는 지도 함께 알고 싶습니다.

감사합니다.

**Comment by yamoo9** [comment]
추후 수업 때 이야기 드릴 것 입니다만.
전역 변수를 사용하는 것은 매우 안 좋은 코딩 습관입니다.

가급적 전역 변수를 사용하지 않는 것이 좋은데요.
자세한 이유는 수업 때 다뤄보도록 하죠 ^^

그리고 함수의 속성을 사용할 경우 전역을 오염시키지 않을 수 있어 장점이 되고,
네임스페이스 패턴으로 함수 객체를 사용 함으로서, 메모리를 위해 별도의 다른 객체를 
안 만들어도 되니 유용합니다 :-)
