### ISSUE TITLE
영상 녹화해주실 수 있나요? 

### ISSUE THREAD

**Issue by peakersky** [yamoo9/JJ_CAMP#16]
안녕하세요 선생님,

첫번째 수업 복습을 위해 수업을 다시 듣고 싶은데, 혹시 다음 수업부터 컴퓨터 스크린 녹화를 해주실 수 없을까 싶어 문의 드립니다. 

이전 이슈를 보니 JJ 정복 CAMP 2016년 6월 18일자 영상 자료가 올라와있는데, 수업마다 이러한 영상을 올려주실 수 있을까요? 

감사합니다

**Comment by yamoo9** [comment]
안녕하세요 @peakersky 님 ^^
스크린 레코딩 요청 주셨는데 죄송하지만 그 요청은 다음과 같은 이유로 들어드리기 어렵습니다 ㅠㅡㅠ

첫째.
매 수업을 녹화(5시간)하고, 
편집하고,
인코딩한 후, 
온라인 상에 업로드 하고, 
링크를 공유하기 까지
상당한 수고가 듭니다.

둘째.
지난 이슈를 통해 공유 되었던 수업 영상은 수업 내용 중 일부이며, 전체 영상이 아닙니다.
지난 1기 수에도 동일한 요청(전체 강의 녹화)을 하신 분이 계셨습니다. 수업을 5시간 듣고 
복습 하기 위해 녹화된 영상을 요청하시는 것일 겁니다. 충분히 요청하시는 이유는 공감합니다.

하지만 녹화된 강의가 매번 제공된다면 정말로 본 수업에 집중할 수 있을까요? 
오히려 "언제든 볼 수 있는 강의"가 되버리게 될테니 본 수업에서의 집중도는 극적으로 떨어질 
것이고, 더 나아가 본 수업에 빠지는 일이 생길 수도 있게 됩니다. 수업을 안 나와도 영상 녹화본이
주어질테니까요. 이런 부작용은 지난 10여년간 강의를 하며 충분히 경험했습니다.

이러한 이유로 정중히 그 요청에 대해 거절 의사를 드립니다. ^^;;

**Comment by peakersky** [comment]
네 확인했습니다. ^^
