### ISSUE TITLE
node 삽입 관련 질문드립니다.

### ISSUE THREAD

**Issue by nicekkong** [yamoo9/JJ_CAMP#17]
첫번째 시간에 수업했던 Node 삽입 관련 문의가 있어서 글 올립니다.

아래와 같은 태그가 있을 경우, 가운데 있는 "중간 P" 앞뒤로 새로 생성한 노드를 삽입하려고 합니다.

``` html
<body>
    <h1>시작</h1>
    <p>중간 P</p>
    <h2>마지막</h2>
</body>
```

수업시간에 배운 메소드인 `insertBefore()` 를 이용하여 다음과 같이 생각해봤습니다.

``` javascript
// 삽입 대상 신규 Node
var new_node = document.createNode('hr');

// h1, p, h2 element 지정
var target_h1 = document.getElementByTagNames('h1').itme(0);
var target_p = document.getElementByTagNames('p').itme(0);
var target_h2 = document.getElementByTagNames('h2').itme(0);

// "중간 P" 앞에 new_node 삽입
document.body.insertBefore(new_node, target_p);

// "중간 P" 뒤에 new_node 삽입
document.body.insertBefore(new_node, target_h2);
```

특정 노드 넣고 싶을때, 항상 신규 노드가 들어갈 뒤의 노드를 찾아서 앞에 넣어야 하는 구조인데
혹시 앞/뒤 노드의 대상이 되는  특정 node를 기준으로 작성하는 메서드나 방법은 따로 없을까요?

질문보다 답변이 짧더라도 설명 부탁드리겠습니다 ^^;;
감사합니다.

**Comment by yamoo9** [comment]
DOM API는 생각하시는 것처럼 편하지 않아 원성이 자자합니다.
jQuery가 사랑 받는 이유이기도 합니다. 😸 

순수한 자바스크립트로 요청하신 문제를 해결하기 위한 방법은 다양합니다.
거론하신 `insertBefore()`와 사용자 정의 함수 `insertAfter()`를 만들어 사용할 수도 있고,
아래와 같이 `insertAdjacentHTML()`을 사용하는 방법도 있습니다.

``` js
// 목표 노드 탐색
var target_p = document.getElementsByTagName('p').item(0);
// 목표 노드 앞/뒤 (형제 노드)에 신규 노드(HTML 코드) 삽입
target_p.insertAdjacentHTML('beforebegin', '<hr>');
target_p.insertAdjacentHTML('afterend', '<hr>');

console.log(target_p.parentNode.outerHTML);
```

이 **수업에서 전하고자하는 가장 중요한 것**은 언어 차원에서, API 차원에서 
지원되지 않는 것은 직접 만들어 쓰면 됩니다. ^^ 앞으로 수업에서 **필요한 것은
모두 만들어 쓸 겁니다.** 그것을 공부하기 위해 오신 것이니 까요~

그럼 다음 수업 시간에 뵙겠습니다.
