### ISSUE TITLE
9 ~ 10 주차 강의 내용이 어떻게 되나요? 

### ISSUE THREAD

**Issue by peakersky** [yamoo9/JJ_CAMP#18]
안녕하세요 선생님~ 

저희 커리큘럼을 보면 10주차에 jQuery 와 Ajax를 다룬다고 나와있는데, 이미 지난 수업에 다루게 된 내용인 것 같습니다. 

다음 오는 9~10 주차 수업에 어떠한 내용을 다루는지 미리 알 수 있을까요? 
백앤드 쪽은 처음 다뤄봐서 예습 필요할 것 같습니다. 
수업에 따로 필요한 개발 환경이 있으면 말씀해주실 수 있을까요? 

수고에 감사합니다. ^^

**Comment by peakersky** [comment]
@yamoo9 이슈 확인부탁드립니다~

**Comment by yamoo9** [comment]
안녕하세요 @peakersky 답변이 늦어 죄송합니다. ^^;
저희가 지난 주에 다룬 Ajax는 jQuery Ajax는 아니고, Native JavaScript Ajax 였습니다.
jQuery Ajax는 Native Ajax를 보다 쉽고 간단하게 사용할 수 있도록 도와줍니다.

9주차 수업에서는 커리큘럼 상 ECMAScript 2015를 다루고,
10주차 수업은 jQuery를 사용하여 UI 컴포넌트를 제작합니다.

수업에서 진행할 개발 환경은 JavaScript Server Side Env. 인 [Node.js](http://nodejs.org/) 입니다. 
수업 시간에 자세히 다뤄볼 것입니다 ^^
