### ISSUE TITLE
질문 있습니다..

### ISSUE THREAD

**Issue by nikki9132** [yamoo9/JJ_CAMP#2]
3일차 수업에 context 질문 드렸던 진현희입니다.

지금 또 코드 보다가 궁금한것은요..
함수 인자는 정의하지 않는 건가요??
------------------------------------------------------- 요 함수 말입니다.
function $queryAll(selector, context) {
  // 유효성 검사(Argument Validation)
  if ( typeof selector !== 'string' ) {
    throw new Error('전달된 인자는 선택자(문자열) 유형이 아닙니다.');
  }
  // 컨텍스트 객체가 존재하지 않는다면...
  if (!context) {
    // 컨텍스트 참조 변수에 document 객체를 참조한다.
    context = document;
  } else {
    // 컨텍스트 객체가 존재한다면...
    // 경우 2. CSS 선택자인 경우
    if ( !context.nodeType && typeof context === 'string' ) {
      context = $query(context);
    }
    // 경우 1. DOM 객체인 경우 (넘어감)
  }
  return context.querySelectorAll(selector);
## }

(selector, context)  ----> 는  정의된게 없는거 같은데...
함수에서 selector는 선택자이고 context는 그 부모라는걸 아는건가요??
어떻게 아는건가요?

**Comment by yamoo9** [comment]
안녕하세요. 현희님 ^^
역시 수업 시간에 이해가 쉽지 않았던 것 같네요. ㅠㅡㅠ 
(보다 쉽게 이해될 수 있도록 노력 하겠습니다!)

질문 주신 내용에 답변 드릴께요.

[ 질문 ]

**함수 정의 과정에서 매개변수는 어떻게 정의 되는가?
(selector, context) ----> 는 정의된게 없는거 같은데...
함수에서 selector는 선택자이고 context는 그 부모라는걸 아는건가요??
어떻게 아는건가요?**

---

[ 답변 ]

**함수를 정의하는 것도, 함수에 전달된 인자를 정의하는 것도 모두 작성자가 설계(Design)합니다.**

함수의 매개변수(Parameters)는 일반 변수 정의와 달리 앞에 `var` 키워드를 붙이지 않고, 
함수 이름 뒤에 붙는 `( )` 안에 추가하는 것으로 정의됩니다.

``` js
// 일반 변수 정의 방법
var 변수이름1;
var 변수이름2 = 값;

// 함수 정의 시에 매개 변수 정의 방법
function 함수이름( 매개변수1, 매개변수2, ..., 매개변수N ) { 
  // 함수 실행 코드 작성 ...
}
```

## 

그리고 첫번째 인자 `selector`가 선택자이고, 두번째 인자 `context`가 부모라는 것을
**함수가 알고 처리하는 것은 아니고, 함수 설계 과정에서 작성자가 정한 규칙(Rule)대로
프로그래밍 하는 것**입니다. 

**함수 제작자가 설정한 함수 사용 방법 규칙**

> 정의된 함수를 사용할 경우, **첫번째 인자**는 **필수 입력사항**으로 **CSS 선택자 문자열**이 와야 한다.
> 만약 그렇지 않을 경우 함수는 사용할 수 없게 되니 오류를 발생한다.
> 
> **두번째 인자**는 **선택사항**으로 **반드시 입력되어야 할 필요는 없다**.
> 입력 값이 없을 경우, 내부적으로 이를 감지하여 `document` 객체로 대체하기 때문이다.
> 
> **만약 값이 전달될 경우, 2가지 유형만 처리할 수 있다**. **하나는 DOM 요소노드**이고, 
> **다른 하나는 CSS 선택자 문자열**이다. 전달된 인자 값이 CSS 선택자 문자열이라면
> $query() 함수를 호출하여 반환된 DOM 요소노드를 컨텍스트로 설정하게 된다.
> 
> **컨텍스트가 결정되면, 함수는 최종적으로 컨텍스트 내부에서 사용자가 전달한 CSS 선택자와
> 일치하는 문서 객체를 반환**한다.

**그래픽 디자인 역시 설계 과정 후, 설계된 규칙에 맞춰 제작을 하죠. 
설계 과정은 디자인이나, 개발이나 유사합니다.**

> 배경 색상이 어둡기 때문에 글자 색상은 밝은 색상으로 와야 한다. 
> 그래야 명도 대비가 분명하여 인식이 쉽기 때문이다. 단, 글자 색상은
> 배경 색상과 유사한 색상을 사용한다.

## 

아래 함수 코드 전문은 위의 규칙에 맞춰 설계된 선언 구문입니다. :-)
수업 시간에 다룬 것보다 좀 더 정리 했으니 코드를 살펴보시고 추가 질문이 생기시면 문의주세요~

``` js
/**
 * @function $queryAll 정의
 *
 * @param  { string }                            selector    CSS 선택자 문자열
 * @param  { undefined | string | ElementNode }  context     컨텍스트 요소노드 (컨텍스트 전달인자가 없을 경우 document 객체로 초기화)
 * @return { NodeList }                                      CSS 선택자로부터 수집된 HTML 콜렉션(Collection)을 반환
 */
function $queryAll(selector, context) {
  // ------------------------------------------------------------------------
  // 유효성 검사(Validation Function Argument)
  // ------------------------------------------------------------------------
  // selector 값이 CSS 선택자 문자열이 아닐 경우 오류 발생
  if (typeof selector !== 'string') {
    throw new Error('전달된 1번째 인자는 CSS 선택자(문자열)이어야 합니다.');
  }
  // context 값이 전달되었는데 요소노드도 아니면서 문자열도 아닌 경우라면 오류 발생
  if ( context && context.nodeType !== 1 && typeof context !== 'string' ) {
    throw new Error('전달된 2번째 인자는 요소노드이거나, CSS 선택자(문자열)이어야 합니다.');
  }

  // ------------------------------------------------------------------------
  // 전달된 컨텍스트가 전달되지 않았거나, 또는 요소노드가 아니고, CSS 선택자 문자열이라면 실행
  // ------------------------------------------------------------------------
  if ( typeof context === 'string' ) {
    context = $query(context);
  }

  // ------------------------------------------------------------------------
  // 수행 결과 반환(Return Function Resule)
  // ------------------------------------------------------------------------
  return (context || document).querySelectorAll(selector);
}
```
