### ISSUE TITLE
선생님, 죄송한데....스크립트 질문은 아닌데요.

### ISSUE THREAD

**Issue by euni100** [yamoo9/JJ_CAMP#5]
혹시 ie 개발자 도구에서 물결무늬 표시가 뜨는  것 무슨 의미인지 아시나요? 주변에 아는 사람이 없어서요... ㅜ_ㅜ
![13754207_10206827547067274_3071824245007781938_n](https://cloud.githubusercontent.com/assets/20013770/17137484/591c0236-5376-11e6-9b1b-ed82ef3a918a.jpg)

**Comment by yamoo9** [comment]
@euni100 님 안녕하세요 ^^

CSS3 신 기능 속성에 대해 IE 웹 브라우저 개발자 도구에서 속성 아래 물결 무늬가 발생한 현상에 대해 문의주셨군요. 간단히 말해 IE 8 이하 버전에서 지원하지 않는 속성 임을 시각적으로 표현한 것입니다. 아래 그림과 호환성 테이블을 확인해보세요.

__문서모드를 IE 8 버전으로 변경한 경우__
![](https://s32.postimg.org/9wtt3zxk5/ie_wave_01.jpg)

__문서모드를 IE 9 버전으로 변경한 경우__
![](https://s32.postimg.org/4mtfqg2p1/ie_wave_02.jpg)

-

### CSS3 브라우저 호환성 테이블
- [box-shadow](http://caniuse.com/#search=box-shadow)
- [border-radius](http://caniuse.com/#search=border-radius)

**Comment by euni100** [comment]
아, 감사합니다. 음, 추가 질문 드릴께요. 죄송합니다.ㅜ_ㅜ ie는 9하고 11에서 테스트 하고 있구요. 서버를 통하기 전에는 이상이 없는데 제우스서버를 통하고 나면 해당속성이 적용이 되지 않고 있습니다. 혹시 짐작 되시는 이유가 있을 까요? ㅜ_ㅜ?

**Comment by yamoo9** [comment]
제우스 서버 환경에서 테스트 해볼 수 없어 정확한 진단은 어렵지만... 아래 글을 참고해 읽어보신 후 테스트 해보시면 어떨까요? ^^;;

[제우스 서버 CSS 적용 문제](http://www.parkgunstyle.kr/209?utm_source=feedburner&utm_medium=feed&utm_campaign=Feed%3A+JuneLife+%28%EB%B0%95%EA%B5%B0%EC%9D%98+%EC%82%AC%EC%A7%84%2C+%EC%9D%BC%EC%83%81%2C+IT+%EC%9D%B4%EC%95%BC%EA%B8%B0%29)

**Comment by euni100** [comment]
감사합니다. 일단 이유는 프레임웍에서 삽입하는 메타태그 인 것 같습니다.

<meta http-equiv="X-UA-Compatible" content="IE=EmulateIE7">

저 메타태그를 공통에서 강제 삽입하고 있더라구요. (-_-);;
ie가 9이하의 경우에 조건 주석문도 삽입해봤는데  사실 브라우저가 물리적으로 9이하인건 아니니깐 실행이 되지 않는것 같습니다. 

저 메타태그를 제거하면 잘 나옵니다. ㅜㅜ

강제 삽입된 메타태그를 인식하지 못하게 하는 방법은 없겠지요?

**Comment by euni100** [comment]
선생님, 해결 됐습니다. 프레임웍에서 페이지 분기가 가능 한 걸 모르고(다들 그런거 없다고 모른다고 해가지고....) 삽....질을 했네요. 수업과 무괸한 질문으로 이슈페이지를 더럽혀서 죄송합니다. ㅜ_ㅜ
