### ISSUE TITLE
서브라임텍스트3 쓰고 있는데요 

### ISSUE THREAD

**Issue by sussjini** [yamoo9/JJ_CAMP#7]
수업과는 조금 다른 질문입니다만,
서브라임텍스트3 에서 바로 validation 확인할수 있나여?
구글링하면 Package Control에 있다는거 같은데 버전마다 다른지 제대로 안나오는거 같고 그래서요 ㅠ

**Comment by yamoo9** [comment]
아래 2개 플러그인이 있어요. 제 경우는 HTML Tidy Linter를 사용중이랍니다 👍 
- [W3​CValidators](https://packagecontrol.io/packages/W3CValidators)
- [SublimeLinter 3 plugin for html tidy](https://github.com/SublimeLinter/SublimeLinter-html-tidy)
