### ISSUE TITLE
오타보고 

### ISSUE THREAD

**Issue by jinyounghwa** [yamoo9/JJ_CAMP#8]
모던 자바스크립트 패턴 부분의 

라이브러리 콜백 패턴

Javascript 라이브러리를 설계할 때, 콜백 패턴은 간단하고 강력한 패턴이라 자주 사용된다. 스프트웨어 라이브러리에 들어갈 코드는 가능한 범용적이고 재사용할 수 있어야 한다.

스프트웨어 -> 소프트웨어 

인 것 같습니다.

**Comment by yamoo9** [comment]
감사합니다 ^^ 수정했습니다.
