### ISSUE TITLE
수업 외 질문입니다^^;;

### ISSUE THREAD

**Issue by pluto1019** [yamoo9/JJ_CAMP#9]
안녕하세요.

저번에도 한번 물어봤었는데요.
angularjs 2.0 공부해 볼려고하는데 책이나 참고사이트, 동영상같은 
추천해주실만한게 있을까요~?

감사합니다~

**Comment by yamoo9** [comment]
국내엔 아직 Angular2 에 대해 다루는 책이 없습니다. [[#참고](http://book.naver.com/search/search.nhn?sm=sta_hty.book&sug=&where=nexearch&query=angular+2)]

참고 사이트, 동영상 강의 추천은 영어라도 괜찮으시다면 ^^
[egghead.io/courses](https://egghead.io/courses)를 살펴보시면 좋을 듯 하네요~
